/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '16-5-23 下午5:40' with Gradle 2.11
 *
 * @author Administrator, @date 16-5-23 下午5:40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
