/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lenovo' at '17-5-8 下午4:05' with Gradle 2.14
 *
 * @author lenovo, @date 17-5-8 下午4:05
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
